### ISSUE TITLE
Gemerkte Angebote analog Europace2.de abfragen

### ISSUE THREAD

**Issue by 8-Ball85** [europace/baufismart-angebote-api#13]
Hallo,
trotz ausgiebiger Recherche der Dokumentation finde ich keinen Zusammenhang des Plattform-Features "Angebot merken".
Ich möchte bereits erstellte Angebote auf der EP2 Plattform auszulesen bevor(!) sie in den Antragsstatus gewechselt wurden (hier ist die Abfrage über das Beratungs-Property wieder möglich). Auf EP2.de werden diese Ermittlungsergebnisse gespeichert um sie mit neuen Ermittlungsergebnissen (z.B. andere Finanzierungswunschvorgaben) zu vergleichen.
Haben Sie da einen Vorschlag?

Vielen Dank und viele Grüße

**Comment by K0ne** [comment]
Hallo,

leider existiert die Möglichkeit noch nicht über die Angebots API ermittelte Angebote zu merken und zu vergleichen. Dies muss noch clientseitig passieren. Wir haben diese Anforderungen in unserer Roadmap und werden sie in einem Projekt umsetzen. Dadurch wird es möglich sein Angebote zu merken, zu vergleichen und zu aktualisieren.
