### ISSUE TITLE
Anbieter Logos nicht abrufbar

### ISSUE THREAD

**Issue by marcelvossmint** [europace/baufismart-angebote-api#15]
Hallo, 
greife ich auf die Logos zu, die für die Produktanbieter zurückgegeben werden, erhalte ich den folgenden Fehler:
Angefragtes Logo:
https://baufismart.api.europace.de/produktanbieter-logos/DSL_BANK.svg
Authorization Header ist gesetzt.

Response:
```                      
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Bad request.

<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: A4TU_RukLX-2X5-eymrh5z84yEwwsxjdwj0P_fWHbUpf3AVxEELGRg==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>

**Comment by K0ne** [comment]
Haben sie es mit dem header:

key: X-Authentication 
value: der JET ohne bearer davor 

versucht?

**Comment by willuhn** [comment]
Gibt es zu diesen Anbieter-Logos eigentlich irgendwo eine Dokumentation? Ich würde die auch gern nutzen, finde aber nirgends einen Hinweis darauf - ausser in diesem Ticket.

**Comment by MikeKrueger75** [comment]
Hallo @willuhn ,

was möchtest du denn mit den Logos tun?

**Comment by willuhn** [comment]
Sie in der Ergebnisliste der Angebote anzeigen, die von https://baufismart.api.europace.de/v2/ergebnisliste/ermittlung zurückgeliefert wurde.
