### ISSUE TITLE
Anschlussfinanzierung liefert keine annehmbaren Angebote

### ISSUE THREAD

**Issue by KoneFuzius** [europace/baufismart-angebote-api#18]
Wenn man eine Anschlussfinanzierung mit Ablösung wählt, dann erhalten wir nur nicht machbare Angebote zurück.

Warum? Die Berechnung benötigt folgende Informationen:

Haushalt + Antragsteller müssen mit angegeben werden. Gehalt auch, wenn die Machbarkeit nicht unter vorbehalt sein soll. Plus die Vorhabenkosten müssen gesetzt sein:

<vorhaben>
<kosten xmlns:xsi=“http://www.w3.org/2001/XMLSchema-instance” xsi:type=“bs:baufiSmartKostenAnschlussFinanzierung”>
</kosten>

**Comment by MikeKrueger75** [comment]
@K0ne 
Was willst du denn hier unternehmen? 
M.E. ist das fachlich korrekt, oder?

**Comment by K0ne** [comment]
Ich würde hier gerne die Dokumentaion anpassen und sichtbarer machen, welche Felder Pflicht sind, um eine Anschlussfinanzierung zu bekommen.

**Comment by KoneFuzius** [comment]
Wir decken Regeln nicht in der Dokumentation ab. Dafür gibt es zu viele und für einzelne Produktanbieter sind diese zu spezifisch. Dafür sehen wir hier die Fachabteilung bzw. auf höherer Flughöhe den API-Evangelisten.
