### ISSUE TITLE
API Authorisation Token anlegen

### ISSUE THREAD

**Issue by MaykAkifovski** [europace/baufismart-angebote-api#19]
Hallo liebe Kollegen,

Ich schreibe gerade einen Python Script, der die Ergebnisliste zu dem Punkt des Angebotsannahme holt und speichert. Dafür brauche ich einen API Authorisation Token. Wäre es möglich einen Token zu bekommen und den immer für die Anfrage zu nutzen, um nicht jedes mal authentifizieren zu müssen?

LG Mayk

**Comment by caspii** [comment]
Hi Mayk,

Es ist ganz einfach sich über die API zu authentifizieren. Komm doch mal rüber und ich zeige es dir.
