### ISSUE TITLE
'405 Method Not Allowed' für 'https://baufismart.api.europace.de/v2/ergebnisliste/ermittlung/<ermittlungsId>'

### ISSUE THREAD

**Issue by MaykAkifovski** [europace/baufismart-angebote-api#20]
Hallo,

Ich bekomme ein 405 Method Not Allowed, wenn ich versuche, die Ergebnisliste auf ''https://baufismart.api.europace.de/v2/ergebnisliste/ermittlung/<ermittlungsId>' abzufragen.
Ablauf ist folgende:
1. Authorisiere mich auf 'https://api.europace.de/login' und bekomme Authorisation Token
2. Mit dem Authorisation Token 'https://baufismart.api.europace.de/v2/ergebnisliste/ermittlung?vorgangsNummer=<vorgansNummer>&alternativen=true' abrufen.
3. Nutze 'ermittlungsId' aus Response um wieder 'https://baufismart.api.europace.de/v2/ergebnisliste/ermittlung/<ermittlungsId>'  abzufragen
4. Als Response bekomme ich 405 Method Not Allowed

Meine Frage ist: Ist mein Ablauf falsch, oder darf ich nicht?

LG Mayk

**Comment by MaykAkifovski** [comment]
Danke Mike, der Fehler lag bei mir. Ich habe POST statt GET Aufruf gemacht.

**Comment by MaykAkifovski** [comment]
Jetzt kommt meine zweite Frage. Kann man die Ergebnisliste für eine vergangene Datum ermitteln? Ich sehe, dass es in der Ermittlungsanfrage 'erstelltAm' gibt. Kann ich eine andere Datum setzen und mich die Ergebnisliste zu dem Zeitpunkt ermitteln?

**Comment by caspii** [comment]
@MaykAkifovski hier sind viele wichtige API Calls in einer Collection gespeichert: https://github.com/europace/api-schnellstart
