### ISSUE TITLE
Übertragen von Präferenzen über die Schnittstellen 'Eli", "Vorgang Anlegen API", "Vorgaenge (auslesen) API"

### ISSUE THREAD

**Issue by prokonzeptGit** [europace/baufismart-angebote-api#25]
Sehr geehrte Damen und Herren,

momentan gibt es keine Möglichkeit Präferenzen über die Schnittstellen zu übertragen:
- Eli
- Vorgang Anlegen API
- Vorgaenge (auslesen) API

Wir würden gerne dieses Feature haben.

Viele Grüße
prokonzept GmbH

**Comment by KoneFuzius** [comment]
@prokonzeptGit Ich hab deine Frage/Wunsch an unseren Produktowner weitergegeben . Er wird deinen Beitrag kommentieren.

**Comment by KoneFuzius** [comment]
Hallo @MarcelEP. Aktuell kann man keine Präferenzen in der Angebots-API übergeben. Kannst du dir das Thema bitte mitnehmen? Danke

**Comment by KoneFuzius** [comment]
Bei erneuter Anfrage klären wir den expliziten Wunsch mit dem Partner...
