### ISSUE TITLE
GetMeldungen liefert nicht die Kategorien zurück

### ISSUE THREAD

**Issue by steegc** [europace/baufismart-angebote-api#30]
Nach dem Ermitteln der Ergebnisliste zu einem Vorgang ermitteln wir die Meldungen zu einem spezifischen Ergebnis.

Das Meldungsobjekt enthält auch eine Kategorie. Diese ist leider nie gefüllt. Das führt dazu, dass wir die Meldungen nicht aufbereiten können und es für unsere Anwender extrem schwer ist zu erkennen, warum ein Angebot rot gescored wurde.

**Comment by KoneFuzius** [comment]
Hallo @steegc,

die "meldungsKategorie" kommt in unseren Testfällen zurück. Könnten sie uns ihren Request & Teil-Response mit Testdaten hier anhängen?

Danke und Liebe grüße

Kone

**Comment by KoneFuzius** [comment]
Kein Feedback...daher close

**Comment by steegc** [comment]
Hallo,

ich weiß nicht warum ich die Mails nicht bekommen habe. Aber auch das hat sich erledigt. 
Die Kategorie hieß zu unserem Zeitpunkt der Implementierung kategorie und noch nicht meldungsKategorie.

Daher wurde das Feld beim Mapping von Json -> POJOs nicht gefüllt.
