### ISSUE TITLE
Keine Möglichkeit der Übertragung von weiteren Daten bei Bestandsobjekten

### ISSUE THREAD

**Issue by steegc** [europace/baufismart-angebote-api#32]
Aktuell ist es nicht möglich bei Bestandsobjekten die Details über die Schnittstelle zu übermitteln, die Auf der Web-UI über den Punkt "Weitere Objektdaten erfassen" eingegeben werden können.

![image](https://user-images.githubusercontent.com/50579927/93750108-44ed8000-fbfb-11ea-8d68-3c15e0f2d6a6.png)

Ohne diese Übermittlung sind keine korrekten Finanzierungen mit Zusatzsicherheit übertragbar.

**Comment by KoneFuzius** [comment]
Hallo @steegc, 

haben Sie (DU? ;)  es schon mit der Entität "BestehendeImmobilie" (siehe [Doku](https://htmlpreview.github.io/?https://raw.githubusercontent.com/hypoport/finanzierungsvorschlaege-api/master/Dokumentation/index.html#_bestehendeimmobilie) probiert?

Viele Grüße

Kone

**Comment by KoneFuzius** [comment]
gab kein Feedback mehr...daher close

**Comment by steegc** [comment]
Entschuldigung, hat sich mir der Kundenangaben-API erledigt.
