### ISSUE TITLE
Potentieller Fehler in der swagger.json

### ISSUE THREAD

**Issue by anderha** [europace/baufismart-angebote-api#38]
**Is your feature request related to a problem? Please describe.**

Potentieller Fehler in der swagger.json im Feld "verwendungszweck" bzw. dessen enum Definition.   

swagger.json: "MODERNISIERUNG_UMmaximalAufzuloesenderWertBAU_ANBAU"
swagger.yaml: "MODERNISIERUNG_UMBAU_ANBAU"   

swagger.json             |  swagger.yaml
:-------------------------:|:-------------------------:
![swagger.json](https://user-images.githubusercontent.com/36031262/110940779-b6e78c00-8337-11eb-96ab-56e982cec128.png)  |  ![swagger.yaml](https://user-images.githubusercontent.com/36031262/110940510-50fb0480-8337-11eb-86ac-98acd80cf005.png)

Ich nehme an "MODERNISIERUNG_UMBAU_ANBAU" ist der korrekte Wert?

**Comment by MikeKrueger75** [comment]
Hallo Alexander, 
du liegst richtig. Wir werden die swagger.json nochmal generieren.
Vielen Dank für den Hinweis.

**Comment by MikeKrueger75** [comment]
fixed in #39
