### ISSUE TITLE
API liefert sporadisch 504 Status Codes

### ISSUE THREAD

**Issue by europacesupport** [europace/baufismart-angebote-api#4]

**Comment by K0ne** [comment]
Exception: Error reading xml: java.util.ConcurrentModificationException.

Problem:
Lag an gleichzeitiger Veränderung eines Java Objekts durch parallele Aufrufe. Der Produktanbieter Resource wurden parallel Links hinzugefügt.

Fix:
Es wird nun immer eine Produktanbieter Resource Instanz erzeugt. Tests hinzugefügt.
