### ISSUE TITLE
element zinsen (summeEndeDerZinsbindung) in Angebote API

### ISSUE THREAD

**Issue by lamelijo** [europace/baufismart-angebote-api#44]
would it be possible to have the above element from GET "v2/ergebnisliste/ermittlung/{ermittlungsId}/ergebnisse/{ergebnisNummer}/zahlungsplaene" 
redundant in GET "/v2/ergebnisliste/ermittlung/{ermittlungsId}/ergebnisse" node "Ergebnisse/Darlehen" as "summeZinsenEndeDerZinsbindung" 

Problem: if you want to display this value in a result display without a complete redemption schedule, you have to call and create it anyway to get this one result.

Thanks and best regards
Jochen

**Comment by KoneFuzius** [comment]
@MarcelEP Hallo Marcel, spricht aus PO Sicht etwas gegen diese Erweiterung. Welche Prio siehst du hier?

**Comment by MarcelEP** [comment]
Hallo Jochen,
wir verstehen eure Herausforderung und euren Wunsch. 
Unsere Philosophie ist, die allg. ErgebnisListe klein und damit schnell zu halten. Details können/sollen durch einen anderen Aufruf nachgeladen werden. 
Das "Aufbohren" der allg. Ergebnisliste um Detailfelder, birgt die Gefahr das genannte Konzept zur Strategie bzgl allg. Liste und Detailliste zu brechen.
Bitte habe Verständnis, dass wir euren Wunsch aktuell ablehnen.
