### ISSUE TITLE
Unklares Verhalten bei Nutzung des Endpunkts der AngeboteAPI mit Vorgangs-ID (Forbidden - 403)

### ISSUE THREAD

**Issue by mgords** [europace/baufismart-angebote-api#49]
Hallo,
über unser Programm wurde ein Vorgang erfolgreich im EA angelegt mit allen notwendigen Daten, u.a. in der Sektion "Finanzbedarf" und bei den "Finanzierungswünschen". Dennoch kann der API-Endpunkt (https://baufismart.api.europace.de/v2/ergebnisliste/ermittlung?vorgangsNummer=...) nicht genutzt werden. Beim Absetzen der Anfrage erscheint eine 403 Response.
Ein Test mittels Postman verlief mit dem gleichen Ergebnis: Nach Autorisation wird die o.g. URL mit der POST - Methode und der Vorgangsnummer als Parameter, aus dem erzeugten Vorgang, versandt. Dennoch erscheint als Response eine "403 - Forbidden" - Rückmeldung. Auch die alte Abfrage über ...v1/finanzierungsvorschlaege“ mit entsprechender Vorgangsnummer funktioniert nicht und es erscheint ebenso 403 (mit Methode GET).
Im Autorisations-Token ist neben anderen auch der Scope "baufinanzierung:angebot:ermitteln" gesetzt und die Autorisation hatte bisher bei anderen Anfragen auch immer funktioniert.
Ist am Vorgang selber etwas falsch? Wie kann genauer analysiert werden, wo der Fehler liegt?
Für Ihre Rückmeldung vielen Dank.

mgo@rds

**Comment by StenValandt** [comment]
@ptrsauer oder @MikeKrueger75  bitte um priorisierte Unterstützung des Entwicklers @mgords bei dem oben geschilderten Thema. Gerne auch als DM (Ticket-Nummer 226160)

**Comment by fgellhorn** [comment]
Hallo @mgords, konnte hier geholfen werden? Ist das Problem noch aktuell?

**Comment by StenValandt** [comment]
Hallo @fgellhorn, das Thema liegt 12 Monate zurück. Es konnte gelöst werden. Thread kann geschlossen werden.
