### ISSUE TITLE
Differenz zwischen Swagger Sepc und Doc

### ISSUE THREAD

**Issue by anderha** [europace/baufismart-angebote-api#59]
Problem:
- Der erfolgreiche Response von [/v2/ergebnisliste/ermittlung](https://github.com/europace/baufismart-angebote-api/blob/6a4a76036fd1255014a741ca031be599cee281f1/angebote-openapi.yaml#L171) wird in der Swagger json/yml mit `302:
          description: "Die Ermittlung wurde erzeugt und ist maximal eine Stunde unter der Url im 'location' Header abrufbar. Beim Abruf der Ermittlung wird der Bearer Token zur Autorisierung erwartet."` beschrieben.
- Laut [Doku](https://docs.api.europace.de/baufinanzierung/angebote/angebote-api/#b-find-offers-without-case) und tatsächlichem Verhalten der API wird aber ein Statuscode 200 mit der Ermittlung im Body als Response geliefert

Auf Basis der Swagger Spec liefern unsere generierten Clients nicht den richtigen Response für den Aufruf des Endpunktes. Liegt hier ein Fehler in unserer Herangehensweise (Verwendung des Endpunktes) vor oder handelt es sich um einen Fehler in der Swagger Spec?

**Comment by andilau** [comment]
Wie es scheint, wurde das abweichende Verhalten mit dem [Release v2.6.2](https://github.com/europace/baufismart-angebote-api/releases/tag/v2.6.2) behoben.
