### ISSUE TITLE
Produktanbieter-Logos funktionieren nicht

### ISSUE THREAD

**Issue by RonaldJaenicke** [europace/baufismart-angebote-api#65]
Ich habe folgendes Problem festgestellt:

Die Links zu den Prouktanbieterlogos aus der Ergebnislister der Baufinanzierungen sind nicht zugreifbar.
z.B.:

curl https://baufismart.api.europace.de/produktanbieter-logos/ING_DIBA.svg

liefert

{
   "timestamp":"2022-09-20T13:05:01.182",
    "traceId":"zuul-api-gatewayf7DGi",
    "statusCode":500,
    "statusMessage":"Internal Server Error",
     "message":"Internal Server Error",
     "path":"/produktanbieter-logos/VB_DUESSELDORF_R.svg"
}

**Comment by fgellhorn** [comment]
Hallo @RonaldJaenicke @StenValandt wir haben die Ursache gefunden und behoben. Die Logos sollten jetzt wieder alle ordnungsgemäß funktionieren.

**Comment by StenValandt** [comment]
@fgellhorn ich kann das leider nur teilweise bestätigen. Ein Teil der Logos wird jetzt wieder von den einzelnen Produktanbietern geladen, von vielen Produktanbietern wird aber weiterhin kein Logo geladen.

**Comment by RonaldJaenicke** [comment]
@fgellhorn  
curl https://www.europace2.de//produktanbieter-logos/OSTSAECHSISCHE_SPK_DRESDEN.svg
 liefert 404

curl https://baufismart.api.europace.de/produktanbieter-logos/ING_DIBA.svg
liefert nach wie vor 500

**Comment by fgellhorn** [comment]
@RonaldJaenicke hier ist ein "/" zuviel hinter xxx.de: https://www.europace2.de//produktanbieter-logos/OSTSAECHSISCHE_SPK_DRESDEN.svg --> https://www.europace2.de/produktanbieter-logos/OSTSAECHSISCHE_SPK_DRESDEN.svg --> hier scheint aber noch ein anderes Problem mit dem Logo der SPK Dresden vorzuliegen, das gebe ich mal weiter

https://baufismart.api.europace.de/produktanbieter-logos/ING_DIBA.svg funktioniert grundsätzlich nicht mehr

**Comment by fgellhorn** [comment]
@RonaldJaenicke Das Logo der Ostsächsischen SPK geht jetzt auch wieder abzurufen
