### ISSUE TITLE
IST: 500 wenn keine Vorgangsberechtigung

### ISSUE THREAD

**Issue by caspii** [europace/baufismart-angebote-api#8]
IST:
https://baufismart.api.europace.de/v2/ergebnisliste/ermittlung?vorgangsNummer=CH6407
Der Server gibt 500 zurück, wenn ich nicht auf den Vorgang zugreifen darf

SOLL:
Hier sollte der passende Response Code kommen (429?) und eine Fehler message.

**Comment by K0ne** [comment]
Der status 403 kommt nun zurück.
