### ISSUE TITLE
Unterschiede in der Machbarkeit der Ergebnisse in ELI und BS

### ISSUE THREAD

**Issue by ollio** [europace/baufismart-angebote-api#9]
**Problem:**
"Und zwar habe ich folgenden Umstand entdeckt, der mir nicht einleuchtet. Bsp.weise befrage ich die API nach Finanzierungsvorschlägen für die folgenden Parameter:
objektArt = HAUS, nutzungsArt = EIGENGENUTZT, kaufpreis = 280000, beschaeftigung/art = ANGESTELLTER, einkommenNettoMonatlich =     15000, annuitaetenDarlehen/darlehensBetrag = 100000, bankUndSparguthaben = 180000 (AUFLOESEN) und erhalte gerade mal drei machbare Ergebnisse"

**Lösung:**

Das Json Request Attribut “ertrag” im bankUndSparguthaben auf "180000" setzen.

“bankUndSparguthaben”: [ {
       “aktuellerWert”: 180000,
       “maximalAufzuloesenderWert”: 180000,
       “ertrag”: 180000,
       “vermoegensEinsatz”: “AUFLOESEN”
}]

Testfall:
T68388

Link zum internen slack Post:
https://europace.slack.com/archives/C31TS2CMN/p1548693764043600

**Comment by KoneFuzius** [comment]
Auch in ELI sind alle Angebote zu dieser Vorgangsnummer machbar.
